### PR TITLE
refactor - remove Linkable in favor of SilverStripe Link

### LINKED ISSUE #15: Linkable no longer maintained
sheadawsons linkable module is no longer maintained, also does not implement any for of permission handling. 
Instead, this module is recommended: https://github.com/gorriecoe/silverstripe-link
Its extremely similar to linkable

### PR DESCRIPTION
**Pull request by jsirish**
fixes #15

### CODE REVIEW

**Comment by jsirish** [comment]
Should we create a new major version for this change?

**Comment by UndefinedOffset** [comment]
Any update on this moving forward? We've been using dynamic/silverstripe-elemental-gallery on a couple projects and this prevents us from upgrading those sites to 4.11.

**Comment by muskie9** [comment]
@UndefinedOffset this fell off our radar a bit, however we discussed today and we feel this is something that we can dedicate time to in the next couple weeks.

I think the PR is overall good (albeit requiring a rebase), we discussed the need for a task to transition from Linkable to LinkField. We're shooting for a basic task to handle the general linking data and hope to have something reviewed shortly.

In the mean time, we did merge some updates to linkable and have successfully updated a few sites to 4.11 with the new [Linkable release](https://github.com/dynamic/silverstripe-linkable/releases/tag/1.1.0). That may help for now while we get this PR sorted.

**Comment by muskie9-opensource** [comment]
After digging into this a bit more, I think a new major version using `gorriecoe/silverstripe-linkfield` is worth releasing to speed things up. A proper migration task will take some looking into, however the modules do seem similar in offering, so some sort of basic task should be feasible.

@jsirish thoughts on this as you did the initial PR?

**Comment by jsirish** [comment]
Now that we found the migration module I think this makes sense, I'm all for it

**Pull request merged**
